### ISSUE TITLE
Fix uniform.like

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#4]
When stepping through the sparrows dataset and fitting a uniform-likelihood detection function, there appeared to be some issues with how the heavy-side function was programmed.  The knee and slope parameters didn't really seem to be accurate, and the slope was difficult to interpret because its sign (+ or -) is reversed.

**Comment by tmcd82070** [comment]
I think ab = (knee)*(slope) is the point at which f(x) = 0.5. But, I have not checked to make sure.

**Comment by tmcd82070** [comment]
I think a better distance function, which is very similar to the heavy side, is 

1 - exp( -(x/s)^k)

The (somebody) and Buckland distance function.  I think we should implement this, and consider eliminating the "uniform".  I am not sure I have that formula correct.

**Comment by jcarlis3** [comment]
The upcoming release (version 1.2) will keep the current parameterization of the uniform likelihood for now.

**Comment by tmcd82070** [comment]
There is no issue with the uniform likelihood.  The problem was my lack of understanding of the parameters.  BEFORE SCALING, f(a) = 0.5. After scaling, f(a/f(0)) is very close to 0.5, assuming g.x.scl = 1.  And, the above depends on parameter b.  If b large, then f(0) is very close to 1 and f(a) is very close to 0.5.

I have updated the help file to accurately describe a and b.  This issue is closed without any changes to code in uniform.like (only changes to uniform.like.Rd).
