### ISSUE TITLE
Clarify `dfuncEstim` help

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#47]
Discussion of required input datasets (e.g., data, detectionData, siteData), which types of covariates are or aren't allowed (site level and/or detection level), etc. needs careful review and updating based on current `Rdistance` functionality.

**Comment by mkleinsa** [comment]
I'm updating the `dfuncEstim` help page. It seems as though we are now using `siteID` in datasets instead of `transectID`, so I am updating the function and documentation to reflect the change in terminology. If I'm wrong on this, let me know. 

I updated the column names in discussion of the input datasets (`detectionData`, `siteData`), and it's consistent now. 

The `Rdistance` functions referred to in `dfuncEstim` are up to date. 

`Observer = "both"` is currently disabled in `dfuncEstim`. 

There is no explanation of `pointID` in arguments. I'm wondering if this is left over from the older version. It's difficult finding information on what `pointID` does or means. 

All examples in the help documentation are up-to-date and working.

**Comment by tmcd82070** [comment]
done in version 2.1.1
