### ISSUE TITLE
Plots not working in autoDistance

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/Rdistance#51]
When plot=F and plot.bs=F, autoDistSamp works just fine. 

`auto <- autoDistSamp(formula=dist~zBare, detectionData=sparrowDetectionData, siteData=sparrowSiteData,
                     w.hi=trunc, plot=FALSE, area=10000, R=10, ci=0.95, plot.bs=FALSE,
                     likelihoods=c("halfnorm", "hazrate","uniform","negexp"),
                     expansions=0)`

But, when plot=T or plot.bs=T, the following error is thrown: 

` Error: object of type 'symbol' is not subsettable `

Traceback:
10. notnull(x$formula) 
9. formula.default(object, env = baseenv()) 
8. formula(object, env = baseenv()) 
7. as.formula(object$call[["formula"]]) at predict.dfunc.R#59
6. terms(as.formula(object$call[["formula"]])) at predict.dfunc.R#59
5. predict.dfunc(x, newdata, type = "parameters") at plot.dfunc.r#132
4. plot.dfunc(dfunc) 
3. plot(dfunc) at autoDistSamp.R#181
2. f.save.result(fit.table, dfunc, like, ser, expan, plot, criterion) at autoDistSamp.R#224
1. autoDistSamp(formula = dist ~ zBare, detectionData = sparrowDetectionData, 
    siteData = sparrowSiteData, w.hi = trunc, plot = TRUE, area = 10000, 
    R = 10, ci = 0.95, plot.bs = FALSE, likelihoods = c("halfnorm", 
        "hazrate", "negexp"), expansions = 0)

**Comment by tmcd82070** [comment]
This error does not occur for pointSurveys.  I.e., plot=T or plot.bs=T in autoDistSamp for point surveys works just fine.

**Comment by jcarlis3** [comment]
I flagged the line in `autoDistSamp` where this error is raised (the first call of `plot(dfunc)` in the function).
I thought it had something to do with the requirement to pass newdata to plot a dfunc with covariates (no newdata was being passed), but that may not be it, since you got the error when using a continuous covariate (which will plot without newdata, see example below).

`data("sparrowDetectionData")`
`data("sparrowSiteData")`

`d1 <- dfuncEstim(dist ~ 1, sparrowDetectionData)`
`plot(d1)  # Plots fine`

`d2 <- dfuncEstim(dist ~ observer, sparrowDetectionData, sparrowSiteData)`
`plot(d2)  # Can't plot without newdata specifying levels of categorical predictor`

`d3 <- dfuncEstim(dist ~ bare, sparrowDetectionData, sparrowSiteData)`
`plot(d3)  # Plots fine, at mean value of covariate across detections`

**Comment by mkleinsa** [comment]
Currently working on fixing the plots bug.

**Comment by mkleinsa** [comment]
The error is probably in `plot(dfunc)` on lines 180 and 279. The issue only arises with categorical predictors in the formula argument. Jason's error in `plot(d2)` is probably an issue with `dfuncEstim` because if I merge the data, the `plot` works fine.

**Comment by tmcd82070** [comment]
Fixed in version 2.1.1
