### ISSUE TITLE
Add kernel scatterplot smoother

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#7]
See kernal.distance.zip from Ryan Nielson.  This will be another option for fitting a detection function.

**Comment by jcarlis3** [comment]
The kernel option currently requires two packages (quantreg and KernSmooth).  Currently, these are loaded (or installed and loaded) on the fly within the function F.density_adaptive within the script kernel.analysis.R.  Might include as dependencies of Rdistance?

Also requires boot

**Comment by tmcd82070** [comment]
Yes, include as dependencies in the DESCRIPTION file.

On Mon, Feb 23, 2015 at 11:05 AM, Jason Carlisle notifications@github.com
wrote:

> The kernel option currently requires two packages (quantreg and
> KernSmooth). Currently, these are loaded (or installed and loaded) on the
> fly within the function F.density_adaptive within the script
> kernel.analysis.R. Might include as dependencies of Rdistance?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/tmcd82070/Rdistance/issues/7#issuecomment-75596879.

## 

 DWH ATTORNEY WORK PRODUCT / ATTORNEY-CLIENT COMMUNICATIONS

_Trent McDonald, PhD *
 *Senior Statistician_

Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
tmcdonald@west-inc.com
 www.west-inc.com

*Follow WEST: *Facebook
http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646
, Twitter http://twitter.com/WestEcoSystems, Linked In
http://www.linkedin.com/company/1458419, Join our Mailing list
http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by jcarlis3** [comment]
boot, quantreg, and KernSmooth have been added to the DESCRIPTION file.

I chose to use the "Imports" option (these packages are required and should install when installing Rdistance), but the "Suggests" route is another option if we're averse to the user having to install extra packages just to use a portion of the Rdistance functionality (boot is used elsewhere, but quantreg and KernSmooth only come into use if using the kernel smoothing method).

**Comment by tmcd82070** [comment]
I was going to suggest "Imports", but did not want to get into it.
 "Imports" is better than "Depends".  Good job.

On Tue, Feb 24, 2015 at 9:10 AM, Jason Carlisle notifications@github.com
wrote:

> boot, quantreg, and KernSmooth have been added to the DESCRIPTION file.
> 
> I chose to use the "Imports" option (these packages are required and
> should install when installing Rdistance), but the "Suggests" route is
> another option if we're averse to the user having to install extra packages
> just to use a portion of the Rdistance functionality (boot is used
> elsewhere, but quantreg and KernSmooth only come into use if using the
> kernel smoothing method).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/tmcd82070/Rdistance/issues/7#issuecomment-75785992.

## 

 DWH ATTORNEY WORK PRODUCT / ATTORNEY-CLIENT COMMUNICATIONS

_Trent McDonald, PhD *
 *Senior Statistician_

Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
tmcdonald@west-inc.com
 www.west-inc.com

*Follow WEST: *Facebook
http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646
, Twitter http://twitter.com/WestEcoSystems, Linked In
http://www.linkedin.com/company/1458419, Join our Mailing list
http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by jcarlis3** [comment]
The kernal-smoothing method of fitting a detection function isn't polished and ready for inclusion in the upcoming release (version 1.2), so I copied the entire CarlisleWorkspace branch that included the kernal-associated files (listed below) into a branch called "KernalSmooth" and removed those files from CarlisleWorkspace.  See commit named "Removed kernal-associated files" on 3/24/15 for more detail.

Files removed:
data\tees.rda
R\F.adaptive.boot.R
R\kernel.analysis.R
vignettes\kernel.example.R

**Comment by tmcd82070** [comment]
References on kernel smoothing method for distance function estimation: 

Wand, M. P., and M. C. Jones. 1995. Kernel smoothing. Chapman&Hall/ CRC, Boca Raton, Florida, USA.

Chen, S. X. 1996. Kernel estimates for density of a biological population using line transect sampling. Journal of Royal Statistical Society, Series C 45:135–150.

Chen, S. X. 1998. Measurement errors in line transect sampling. Biometrics 54:899–908.

Chen, S. X. 1999. Estimation in independent observer line transect surveys for clustered populations. Biometrics 55:754–759.

Chen, S. X. 2000. Animal abundance estimation in independent observer line transect surveys. Environmental and Ecological Statistics 7:285–299.

**Comment by tmcd82070** [comment]
Kernel density smoothing have associated print and plot and abundance methods has been implemented as of version 2.1.0 of Rdistance.  See function distSmu.
