### ISSUE TITLE
How can I tell if the fit has problems (such as "negative g(x)?"  from dfuncEstim 

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tmcd82070/Rdistance#70]
I'm fitting several different detection functions and using AIC to sort them etc. The $convergence !=0 is helpful in identifying fits that do not converge so I can remove them from the model set.

However, in several cases, the "best model" (lowest AIC) has problem such as probabilities <0 that are only apparent when plotted. 

For example, in the attached code, the "best" function (by AIC criteria) has problems with the fit (negative values)?

How can I identify these in advance? 

If I could likely get predictions of the g(x) function for many values of x, I could search to see if any are negative, but I can't figure out how to get estimates of g(x) or the detection function at given values of x. It would be nice to have something like:
gx <- predict(dist.func.fit, x=seq(0,100,1), type="gx") # give the combined distance x area searched
dx <- predict(dist.funct.fit, x=seq(0,100,1), type='df') # give the detection probability

Or, is there a way to "extract" any warning message from the plot window?

Attached R code and example files.
[example.R.txt](https://github.com/tmcd82070/Rdistance/files/2403912/example.R.txt)
[example.xlsx](https://github.com/tmcd82070/Rdistance/files/2403913/example.xlsx)

Or extract from (including  html  notebook output)
https://www.dropbox.com/sh/1e3pd2e1kaq3rzd/AAA7jP1e2-szp6o7Vg9ZLvAPa?dl=0

Thanks

Carl.

**Comment by tmcd82070** [comment]
@cschwarz-stat-sfu-ca : clever use of lplyr for fitting distance functions in example.R.txt

**Comment by tmcd82070** [comment]
There is a predict method in `Rdistance`; but, the `predict` method currently only predicts parameters of the distance function, not the distance functions themselves.  It is a difficult issue because there are, potentially, separate parameters for each detection when covariates are present. Each of those parameter sets expand into a distance function.  So, it is not clear to me what's the best thing to do. 

I will implement a `type=dfunc` argument in the `predict` method that will do what @cschwarz-stat-sfu-ca suggests and wants.  

In the mean time, here is a function that tests for the presence of negative probabilities.  It only works without covariates (i.e., distance function cannot contain covariates).  If the distance function does contain covariates, it would be relatively easy to call `predict.dfunc` and loop through each of the parameter sets testing for negatives. 

```
  hasNegPredictions <- function(dfunc){
    # This is a patch.  Will only work when dfunc 
    # contains no covariates. 
    like <- match.fun(paste0(dfunc$like.form,".like"))
    d <- seq(dfunc$w.lo, dfunc$w.hi, length=100)
    f <- like(dfunc$parameters, dist=d, 
              expansions = dfunc$expansions, 
              w.lo=dfunc$w.lo, 
              w.hi=dfunc$w.hi, 
              series = dfunc$series, 
              pointSurvey=dfunc$pointSurvey)  # this is f, not g; f is not scaled 
    any(f<0)
  }
``` 

This function can be incorporated into the fitting loop of the example.  If a dfunc yields negative predictions, AIC is set to Inf which effectively removes it.  In my loop, I save which dfuncs contain negative predictions (`negPred` field).  Here is the loop part of my modified example code: 

```
  # fit the detection function to the set and find the best fitting detection using AIC
  detect.func.set <- plyr::dlply(detect.set, "detect.fun", function(x){
      detect.func <- dfuncEstim(formula=dist~1, w.hi=100,
                            detectionData=detect.df,
                            siteData     =site.df,  # needed if site lavel covariates are needed
                            pointSurvey=TRUE,
                            likelihood=x$detect.likelihood.function, expansions=x$detect.expansions)
      #browser()
      AIC=ifelse(detect.func$convergence==0, AIC(detect.func), Inf)
      if(hasNegPredictions(detect.func)){
        AIC <- Inf
        negPreds <- TRUE
      } else {
        negPreds <- FALSE
      }
      
      list(detect.fun=detect.func, AIC=AIC, negPreds=negPreds)
  })
  #browser()
  # find the min AIC
  detect.fun.AIC <- plyr::ldply(detect.func.set, function(x){data.frame(AIC=x$AIC, negPreds=x$negPreds)})
  detect.fun.AIC
  detect.func <- detect.func.set[[ which.min(detect.fun.AIC$AIC)]]$detect.fun
```

**Comment by cschwarz-stat-sfu-ca** [comment]
Perfect. Works like a charm....Thanks. Carl.

________________________________
