### ISSUE TITLE
Gamma detection function for point surveys gives very odd results? 

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tmcd82070/Rdistance#71]
I tried fitting a Gamma detection function to the point count data and got very strange results.
  detect.fun      AIC       EDR     like
1          1 967.3043 56.324537 halfnorm
2          2 958.6887 62.438469  hazrate
3          3 965.8668 60.535903  uniform
4          4 980.1623 44.375203   negexp
5          5 947.8099  9.122768    Gamma

The Gamma appears to be the best fitting curve, the resulting plot looks fine (run the code), but the EDR is very odd. Something funky is happening here that the AIC claims it is a good fit, the plot on the surface looks fine, but look at the scale of the density axis (!), but the EDR doesn't seem to match the plot.

Code available at:
    https://www.dropbox.com/sh/u20pjtztfajming/AAC_C7QfNdo8t8wNJSKYsFsxa?dl=0

or attached
[example.R.txt](https://github.com/tmcd82070/Rdistance/files/2412614/example.R.txt)
[example.xlsx](https://github.com/tmcd82070/Rdistance/files/2412615/example.xlsx)

Thanks again

Carl Schwarz

**Comment by tmcd82070** [comment]
Again, a bug in the Gamma likelihood (only) that was a product of incomplete testing of point transects and the gamma likelihood.  Point transects and gammas are not popular combinations.  Thank you @cschwarz-stat-sfu-ca . 

Error was incorrect scaling of gamma likelihood when completing the EDR computations.  For fitting, we want all likelihoods to integrate to 1.0.  This was happening for our `Gamma.like` function because we called `dgamma` internally, which was pre-scaled to be a pdf.  But, when we compute EDR, we want the gamma likelihood scaled to some number specified by the user.  We want g(x.scl) = g.x.scl, or in the case of gamma we want g(mode) = 1 (usually). This scaling was not happening.  We were computing EDR of f(x), not g(x), when f(x) was the Gamma.  This has not been corrected. 

The above bug did not effect AIC or estimated parameters because scaling was correct (i.e., we were correctly using f(x)). 

A couple minor improvements to `EDR` were implemented but previous version worked fine.
