### ISSUE TITLE
Object in dataset but getting return Error: object not found

### ISSUE THREAD

**Issue by rbonoan** [tmcd82070/Rdistance#75]
I am following the "Modeling abundance in relation to covariates" script to analyse my distance data with week the survey was done as a covariate. For context, I used distance sampling and line transects to survey my field site for butterflies once a week for eight weeks. The butterflies live longer than one week so I'd like to get estimate for each week I surveyed the site.

When I run the initial code for dfuncEstim(), the detection function is successfully fit with the formula distance~week. When I go to plot the data however, I get the following error. 

**Error in eval(predvars, data, env) : object 'week' not found**

I have checked and re-checked my dataset and the object "week" does in fact exist. I get the same error when continuing with the code to estimate abundance per week. See my code and beginning of dataset below.

Am I missing something??

```
# detection data.frame
detect=read.csv("detection 2019.csv") 
head(detect)

detect2=subset(detect,sex!="F") #exclude females
head(detect2)
```

 siteID week      date dist behavior groupsize sex prop..PBB.total. species    patch
1    102    0 5/13/2019  0.0  Sitting         1   M                0     SBB unburned
2    102    0 5/13/2019  0.0  Sitting         1   M                0     SBB unburned
3    104    0 5/13/2019  1.0   Flying         1   M                0     SBB unburned
4    106    0 5/13/2019  0.0   Flying         1   M                0     SBB unburned
5    106    0 5/13/2019  0.5   Flying         1   M                0     SBB unburned
6    106    0 5/13/2019  0.0   Flying         1   M                0     SBB unburned

```
# transect data.frame
sites=read.csv("sites 2019.csv")
head(sites)
```
siteID length obs week      date start  end temp temp2 wind wind2 cloud cloud2    patch
1    102    124  RB    0 5/13/2019  1315 1320   66  warm    1   low    70   high unburned
2    202     35  RB    0 5/13/2019  1315 1320   66  warm    1   low    70   high burned17
3    204    104  RB    0 5/13/2019  1321 1325   66  warm    2  high    70   high burned17
4    104    239  RB    0 5/13/2019  1321 1325   66  warm    2  high    70   high unburned
5    106    275  RB    0 5/13/2019  1325 1340   68  warm    2  high    80   high unburned
6    206    173  RB    0 5/13/2019  1325 1340   68  warm    2  high    80   high burned17
             site
1 Johnson Prairie
2 Johnson Prairie
3 Johnson Prairie
4 Johnson Prairie
5 Johnson Prairie
6 Johnson Prairie

```
# Fit a detection function

# First, explore the distribution of distances
hist(detect2$dist, col="grey", main="", xlab="distance (m)")
summary(detect2$dist)

# For line transects, Buckland et al. recommend truncating 5-10% of distances
quantile(detect2$dist, c(0.5, 0.85, 0.9, 0.95, 1))

# Going to truncate at 3 m 
trunc <- 3

hist(detect2$dist[detect2$dist <= 3],
     breaks=15, col="grey", main="", xlab="Distance (m)")

# combine transect (siteID) and week to make unique siteIDs
detect.wk=detect2 #make unique transect ID for each week
detect.wk$siteID=paste(detect.wk$siteID, detect.wk$week, sep="_") 
head(detect.wk)
```
siteID week      date dist behavior groupsize sex prop..PBB.total. species    patch
1  102_0    0 5/13/2019  0.0  Sitting         1   M                0     SBB unburned
2  102_0    0 5/13/2019  0.0  Sitting         1   M                0     SBB unburned
3  104_0    0 5/13/2019  1.0   Flying         1   M                0     SBB unburned
4  106_0    0 5/13/2019  0.0   Flying         1   M                0     SBB unburned
5  106_0    0 5/13/2019  0.5   Flying         1   M                0     SBB unburned
6  106_0    0 5/13/2019  0.0   Flying         1   M                0     SBB unburned

```
sites.wk=sites #make unique transect ID for each week
sites.wk$siteID=paste(sites$siteID, sites$week, sep="_") 
head(sites.wk)
```
siteID length obs week      date start  end temp temp2 wind wind2 cloud cloud2    patch
1  102_0    124  RB    0 5/13/2019  1315 1320   66  warm    1   low    70   high unburned
2  202_0     35  RB    0 5/13/2019  1315 1320   66  warm    1   low    70   high burned17
3  204_0    104  RB    0 5/13/2019  1321 1325   66  warm    2  high    70   high burned17
4  104_0    239  RB    0 5/13/2019  1321 1325   66  warm    2  high    70   high unburned
5  106_0    275  RB    0 5/13/2019  1325 1340   68  warm    2  high    80   high unburned
6  206_0    173  RB    0 5/13/2019  1325 1340   68  warm    2  high    80   high burned17
             site
1 Johnson Prairie
2 Johnson Prairie
3 Johnson Prairie
4 Johnson Prairie
5 Johnson Prairie
6 Johnson Prairie
```
# Next, fit a detection function (plotted as a red line) using `dfuncEstim`
butter.dfunc <- dfuncEstim(formula=dist~week,
                            detectionData=detect.wk,
                            siteData=sites.wk,
                            likelihood="negexp", w.hi=trunc)

butter.dfunc
```
Call: dfuncEstim(formula = dist ~ week, detectionData = detect.wk, siteData = sites.wk,
   likelihood = "negexp", w.hi = trunc)
Coefficients:
             Estimate     SE            z            p(>|z|)  
(Intercept)  -0.01429401  2.596465e-01  -0.05505181  0.9560972
week          0.00000000  5.931642e+04   0.00000000  1.0000000

Convergence: Success
Function: NEGEXP  
Strip: 0 to 3 
Average effective strip width (ESW): 0.9617138 
Average probability of detection: 0.3205713 
Scaling: g(0) = 1
Log likelihood: 23.96639 
AICc: 52.37723

```
plot(butter.dfunc, #ERROR: object "week" not found
     newdata=data.frame(week=unique(levels(sites.wk$week))))
```
Error in eval(predvars, data, env) : object 'week' not found

**Comment by tmcd82070** [comment]
Thank you for the note.  I see nothing obviously wrong with your workflow.
I will dive deeper into this, but give me a few days.

*Trent McDonald*
* Senior Statistician*

Western EcoSystems Technology, Inc.
Environmental & Statistical Consultants
1610 Reynolds Street
Laramie, WY 82072
307-721-3172
307-755-9717
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by tmcd82070** [comment]
@rbonoan : I suspect something was wrong with your "newdata" data frame in the plot statement. If `site.wk$week` was not a factor, `levels(site.wk$week)` will return NULL and newdata will be empty. Check that.  Alternatively, set `newdata=data.frame(week=c(0,1,2,3))`. 

I note you have `week` in both data sets.  Rdistance merges on the common names among the detection and site data.  Hence, in your example Rdistance merges by c("siteID", "week").  That is probably not what you want.  Remove `week` from the `detects.wk` data frame (Rdistance allows only transect level covariates) so that the merge is only by `siteID`.  But, even with `week` in both data frames, Rdistance still plots on my end, so I think your original problem was null `levels`.  

Here is a minimum working example showing that the newdata argument works: 

```
> set.seed(848448)
> nDetects <- 30
> nTrans <- 10
> reps <- rpois(nDetects, 2.3)
> detect.wk <- data.frame(
+   siteID = rep(101:(100+nTrans), each=nDetects/nTrans),
+   dist = rgamma(nDetects, 1)
+ )
> head(detect.wk)
  siteID      dist
1    101 0.1113293
2    101 1.6703973
3    101 0.2461223
4    102 2.4298296
5    102 2.7224680
6    102 2.2254035
> dim(detect.wk)
[1] 30  2
> 
> sites.wk <- data.frame(
+   siteID = unique(detect.wk$siteID),
+   length = rpois(length(unique(detect.wk$siteID)), 100),
+   week = c(rep(0:2, each=3), 2)
+ )
> head(sites.wk)
  siteID length week
1    101     92    0
2    102     99    0
3    103     79    0
4    104     99    1
5    105    103    1
6    106    102    1
> dim(sites.wk)
[1] 10  3
> 
> butter.dfunc <- dfuncEstim(formula=dist~week,
+                            detectionData=detect.wk,
+                            siteData=sites.wk,
+                            likelihood="negexp")
> 
> butter.dfunc
Call: dfuncEstim(formula = dist ~ week, detectionData = detect.wk, siteData
   = sites.wk, likelihood = "negexp")
Coefficients:
             Estimate    SE         z          p(>|z|)  
(Intercept)  -0.6131018  0.5275140  -1.162247  0.2451350
week          0.3555276  0.3140365   1.132122  0.2575832

Convergence: Success
Function: NEGEXP  
Strip: 0 to 3.19427820764375 
Average effective strip width (ESW): 1.162941 
Average probability of detection: 0.3640701 
Scaling: g(0) = 1
Log likelihood: 27.0534 
AICc: 58.55124

> 
> myNewData <- data.frame(week=unique(sites.wk$week))
> myNewData
  week
1    0
2    1
3    2
> 
> plot(butter.dfunc, newdata=myNewData)
> 
```

![image](https://user-images.githubusercontent.com/4823244/82766446-851f2c00-9ddc-11ea-9002-47764ce12886.png)
